### ISSUE TITLE
Roadmap for 0.5

### ISSUE THREAD

**Issue by mudlord** [mudlord/shaderlathe#1]
- [ ] Fix timing deadlock when GNU rocket sync is active.

- [ ] Add tabbed shader GUI controls

- [ ] Add multiple post process passes

- [ ] Work out basic effect/sync bundle for project files

- [ ] Add basic Win32 menu for loading project files.

**Comment by mudlord** [comment]
Removed sync with libretro shaders, with current design in progress, should be enough.
